# -*- coding: utf-8 -*-

from . import abstract_models
from . import item_code_identity
from . import item_desc_spec_particular
from . import uom_uom
from . import product_template
from . import item_desc_spec
from . import res_partner
from . import ideatime_client_address
from . import customer_region
from . import ideatime_project_info
from . import jo_acceptance
from . import task_survey
from . import pic
from . import ideatime_survey
from . import res_users
from . import order_agreement
from . import material_identity
from . import calendar
from . import sale_order
from . import project
from . import stock
from . import expense_voucher
from . import hr_employee
from . import mail_activity
from . import product_attribute
from . import account_move
from . import project_type
from . import cost_option
from . import design_proposal
from . import shop_type
from . import shop_list
from . import project_task_type
from . import account_payment
